apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-config
data:
  config.json: |
    {
      "environment" : "dev"
    }
# kubectl create configmap kubernetes-config --from-file ./golang/configs/config.json
