apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-dashboard
  ports:
    - protocol: TCP
      name: http
      port: 443
      targetPort: 8443