apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deploy
spec:
  template:
    spec:
      containers:
      - name: kubernetes-dashboard
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"